/**
 * In-app auto-update (Tauri desktop only).
 *
 * The updater endpoint is the GitHub release feed (latest.json, generated by
 * tauri-action). Updates are signature-verified against the pubkey baked into
 * the app, so a clinic machine can update itself over any internet
 * connection without re-downloading the installer from the releases page.
 *
 * Flow: check() on a schedule → if an update exists, surface a non-blocking
 * banner (never force an interrupt mid-consultation) → user clicks
 * "Download update" → progress → NSIS installer runs in passive mode and the
 * app relaunches. On Windows the install step exits the app automatically,
 * so save pending DB writes first via the offline flush.
 */

import { check, type Update } from "@tauri-apps/plugin-updater";
import { relaunch } from "@tauri-apps/plugin-process";
import { isTauriDesktop, flushDatabase } from "@/offline/activate";

export interface UpdateState {
  /** Update metadata available from the feed. */
  version: string;
  notes: string;
  /** "available" → idle prompt; "downloading" → progress 0..1; "ready" → restart pending. */
  phase: "available" | "downloading" | "ready";
  /** 0..1 download progress; only meaningful while downloading. */
  progress: number;
}

type Listener = (state: UpdateState | null) => void;

let listeners = new Set<Listener>();
let state: UpdateState | null = null;
let checked = false;
let checkTimer: number | null = null;

/** Notify React subscribers (the settings card / banner). */
function emit(next: UpdateState | null): void {
  state = next;
  for (const l of listeners) l(state);
}

export function subscribeToUpdates(listener: Listener): () => void {
  listeners.add(listener);
  listener(state);
  return () => listeners.delete(listener);
}

export function getUpdateState(): UpdateState | null {
  return state;
}

export function isUpdateSupported(): boolean {
  return isTauriDesktop();
}

/**
 * Query the update feed once. Safe to call repeatedly: the first call starts
 * the hourly re-check timer, and in-flight checks are deduplicated.
 */
let checking: Promise<string | null> | null = null;

export function checkForUpdates(): Promise<string | null> {
  if (!isUpdateSupported()) return Promise.resolve(null);
  if (checking) return checking;
  checking = (async () => {
    try {
      const update: Update | null = await check({ timeout: 15_000 });
      if (!update) return null;
      if (state?.phase === "downloading") return state.version; // already on it
      emit({ version: update.version, notes: update.body ?? "", phase: "available", progress: 0 });
      return update.version;
    } catch {
      // Offline, feed unreachable, or signature endpoint down — silent retry
      // on the next interval. Updates must never nag or error-modal the user.
      return null;
    } finally {
      checking = null;
    }
  })();
  return checking;
}

/**
 * Download and install the pending update, then relaunch. The returned
 * promise resolves when the installer has been launched — on Windows the
 * app is killed by the installer at that point.
 */
export async function installUpdate(): Promise<void> {
  if (!isUpdateSupported()) return;
  const current = state;
  if (!current) return;
  emit({ ...current, phase: "downloading", progress: 0 });
  // Re-check to obtain a fresh Update handle (handles are single-use).
  const update = await check({ timeout: 15_000 });
  if (!update) {
    emit(null);
    return;
  }
  let total = 0;
  await update.downloadAndInstall((event) => {
    switch (event.event) {
      case "Started":
        total = event.data.contentLength ?? 0;
        break;
      case "Progress":
        if (total > 0) {
          emit({
            ...state!,
            phase: "downloading",
            progress: Math.min(0.99, (state!.progress * total + event.data.chunkLength) / total),
          });
        }
        break;
      case "Finished":
        break;
    }
  });
  // The NSIS installer is about to terminate this process on Windows; push
  // any debounced DB writes to IndexedDB first (best effort, fire-and-forget).
  flushDatabase();
  emit({ version: update.version, notes: current.notes, phase: "ready", progress: 1 });
  await relaunch();
}

/** Hourly re-check; the clinic leaves the app open all day. */
const CHECK_INTERVAL_MS = 60 * 60 * 1000;

/**
 * Start the background update poller. Mount once from the app shell
 * (desktop only); returns a cleanup function.
 */
export function startUpdatePoller(): () => void {
  if (!isUpdateSupported()) return () => undefined;
  // Give the app time to boot and the clinic a moment before the first probe.
  const initial = window.setTimeout(
    () => {
      void checkForUpdates();
      checkTimer = window.setInterval(() => void checkForUpdates(), CHECK_INTERVAL_MS);
    },
    60_000,
  );
  return () => {
    window.clearTimeout(initial);
    if (checkTimer !== null) window.clearInterval(checkTimer);
  };
}

/** Reset module state for tests. */
export function __resetUpdateStateForTests(): void {
  listeners = new Set();
  state = null;
  checked = false;
  if (checkTimer !== null) {
    window.clearInterval(checkTimer);
    checkTimer = null;
  }
}
